### PR TITLE
professionalism

### PR DESCRIPTION
**Pull request by Zazama**
applying what we learned in sopra thx

### CODE REVIEW

**Comment by baabaablackgoat** [comment]
Context

**Review by baabaablackgoat — CHANGES_REQUESTED** [review]
I think we could expand the magic variable avoiding onto every string that exists, ever.

**Comment by Zazama** [comment]
We could also create an Array that holds the consts in order to access them easier.

e.g.

```javascript
const fuckingZero = 0;
const fuckingOne = 1;
const fuckingTwo = 2;
const numbers = [fuckingZero, fuckingOne, fuckingTwo];

// Then you can just use
"helloworld".substr(numbers[fuckingOne], numbers[fuckingTwo]);
```

What do you think?

**Comment by baabaablackgoat** [comment]
> 
> 
> We could also create an Array that holds the consts in order to access them easier.
> 
> e.g.
> 
> ```js
> const fuckingZero = 0;
> const fuckingOne = 1;
> const fuckingTwo = 2;
> const numbers = [fuckingZero, fuckingOne, fuckingTwo];
> 
> // Then you can just use
> "helloworld".substr(numbers[fuckingOne], numbers[fuckingTwo]);
> ```
> 
> What do you think?

**Review by baabaablackgoat — APPROVED** [review]
👌

**Pull request closed without merging**
